version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.10
    working_directory: ~/repo
    environment:
    - FLOW_API_KEY: fake
    steps:
      - checkout
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
